# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_description',
            field=models.TextField(default=set),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=200),
        ),
    ]
